update

diff --git a/script/script_option b/script/script_option
--- a/script/script_option
+++ b/script/script_option
@@ -8,8 +8,12 @@
 # System Required: Debian/Ubuntu
 # Version: 1.0
 #=============================================================
+
+curr_date=$(date "+%Y-%m-%d %H:%M:%S")
+setcolor
+
 ################## 字体格式设置 ##################
-function setcolor() {
+setcolor() {
   black=$(tput setaf 0)
   red=$(tput setaf 1)
   green=$(tput setaf 2)
@@ -51,7 +55,7 @@ function setcolor() {
 ################## 检查root权限 ##################
 check_root() {
   if [[ $EUID -ne 0 ]]; then
-    echo -e "${Red}Error:本脚本必须root账号运行，请切换root用户后再执行本脚本!${END}"
+    echo -e "${red}Error:本脚本必须root账号运行，请切换root用户后再执行本脚本!${normal}"
     exit 1
   fi
 }
@@ -59,7 +63,7 @@ check_root() {
 ################## 检查VPS架构 ##################
 check_vz() {
   if [[ -d "/proc/vz" ]]; then
-    echo -e "${Red}Error:您的VPS是openVZ架构，臣妾办不到啊!${END}"
+    echo -e "${red}Error:您的VPS是openVZ架构，臣妾办不到啊!${normal}"
     exit 1
   fi
 }
@@ -86,4 +90,56 @@ check_rclone() {
   if [ ! -f /usr/bin/fclone ]; then
     wget -qN https://github.com/cgkings/script-store/raw/master/tools/fclone-v0.4.1-linux-amd64.zip && unzip -qo fclone-v0.4.1-linux-amd64.zip -d /usr/bin/ && rm -f fclone-v0.4.1-linux-amd64.zip && chmod +x /usr/bin/fclone && fclone version
   fi
+}
+
+################## 检查安装情况 ##################
+check_release() {
+  if [[ -f /etc/redhat-release ]]; then
+    release='centos'
+  elif cat /etc/issue | grep -q -E -i "debian"; then
+    release='debian'
+  elif cat /etc/issue | grep -q -E -i "armbian"; then
+    release='armdebian'
+  elif cat /etc/issue | grep -q -E -i "ubuntu"; then
+    release='ubuntu'
+  elif cat /etc/issue | grep -q -E -i "redhat|red hat|centos"; then
+    release='centos'
+  elif cat /proc/version | grep -q -E -i "debian"; then
+    release='debian'
+  elif cat /proc/version | grep -q -E -i "ubuntu"; then
+    release='ubuntu'
+  elif cat /proc/version | grep -q -E -i "redhat|red hat|centos"; then
+    release='centos'
+  fi
+  sys=$(uname -m)
+}
+
+check_command() {
+  check_release
+  for command_arges in $*
+  do
+  command_status=$(dpkg --get-selections | grep $command_arges)
+  if [ -z $command_status ]; then
+    echo -e "$(curr_date) ${red}$command_arges${normal} 不存在.正在为您安装，请稍后..."
+    if [[ "${release}" = "centos" ]]; then
+      yum install $command_arges -y
+    elif [[ "${release}" = "debian" || "${release}" = "ubuntu" || "${release}" = "armdebian"  ]]; then
+      apt-get update --fix-missing -y && apt upgrade -y
+      apt-get install $1command_arges -y
+    else
+      echo -e "$(curr_date) ${red}对不起！您的系统暂不支持该脚本，请联系作者做定制优化，谢谢！${normal}"
+      exit 1
+    fi
+  fi
+  done
+}
+
+################## 检查目录情况 ##################
+check_dir_file(){
+  if [ "${1:0-1:1}" = "/" ] && [ -d "$1" ];then
+    return 0
+  elif [ -f "$1" ];then
+    return 0
+  fi
+  return 1
 }
